version: "3.9"

services:
  mysql:
    image: mysql:8.0
    container_name: mysql_a3
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: PROJETOA3
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
